#%RAML 1.0
title: Automated patron blocks
version: v0.1
baseUri: http://github.com/org/folio/mod-feesfines

documentation:
  - title: API for checking if any automated patron blocks exist for patron
    content: <b>Automated patron blocks API</b>

types:
  user: !include user.json
  loanPolicy: !include loan-policy.json
  loan: !include loan.json
  errors: !include raml-util/schemas/errors.schema
  automatedPatronBlocks: !include automated-patron-blocks.json
  synchronizationRequest: !include synchronization-request.json
  synchronizationResponse: !include synchronization-response.json
  synchronizationJob: !include synchronization-job.json

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml

/automated-patron-blocks:
  /{userId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: automatedPatronBlocks
              example: !include examples/automated-patron-blocks.sample
        400:
          description: "Invalid user ID in request"
          body:
            text/plain:
              example: "Bad request, e.g. invalid user UUID"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
  /synchronization:
    /request:
      post:
        body:
          application/json:
            type: synchronizationRequest
        responses:
          201:
            description: "Synchronization was done successfully"
            body:
              application/json:
                type: synchronizationResponse
                example: !include examples/synchronization-response.sample
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error, please contact administrator"
      /{syncRequestId}:
        get:
          description: "Checks synchronization status"
          responses:
            200:
              body:
                application/json:
                  schema: synchronizationJob
                  example: !include examples/synchronization-job.sample
            404:
              description: "The request was not found"
              body:
                text/plain:
                  example: "Bad request, e.g. invalid user UUID"
            500:
              description: "Internal server error, e.g. due to misconfiguration"
              body:
                text/plain:
                  example: "Internal server error, contact administrator"
    /run:
      post:
        responses:
          202:
            description: "Synchronization request has been accepted for processing"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error, please contact administrator"
