#%RAML 1.0

title: Event handlers API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Event handlers API
    content: <b>API for consuming events</b>

types:
  errors: !include raml-util/schemas/errors.schema
  fee-fine-balance-changed-event: !include events/fee-fine-balance-changed.json
  item-checked-out-event: !include events/item-checked-out.json

resourceTypes:
  event-handler:
    description: "Handler for <<resourcePathName | !upperunderscorecase>> events"
    post:
      body:
        application/json:
          type: <<resourcePathName>>-event
      responses:
        204:
          description: "Event received successfully"
        400:
          description: "Bad request"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"

/automated-patron-blocks/handlers:
  description: "Handlers for events the module is subscribed to"
  /fee-fine-balance-changed:
    type: event-handler
  /item-checked-out:
    type: event-handler
